"""add access profiles and contract support tables

Revision ID: d24610c09828
Revises: 5bdcdc88aa12
Create Date: 2026-05-30 12:33:45.441374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24610c09828'
down_revision: Union[str, Sequence[str], None] = '5bdcdc88aa12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_profiles_id'), 'access_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_access_profiles_name'), 'access_profiles', ['name'], unique=True)
    op.execute(
        """
        INSERT INTO access_profiles (name, description, is_active, created_at, updated_at)
        VALUES
            ('Administrator', 'Full administrative access.', true, NOW(), NOW()),
            ('Executive Board', 'Executive visibility for strategic indicators.', true, NOW(), NOW()),
            ('Contracts', 'Contract management and operational access.', true, NOW(), NOW()),
            ('Financial', 'Financial analysis and remuneration table access.', true, NOW(), NOW()),
            ('Audit', 'Audit and compliance review access.', true, NOW(), NOW()),
            ('Read Only', 'Read-only access to contract information.', true, NOW(), NOW())
        ON CONFLICT (name) DO NOTHING
        """
    )
    op.create_table('contract_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('reference_year', sa.Integer(), nullable=False),
    sa.Column('adjustment_index', sa.String(length=100), nullable=True),
    sa.Column('applied_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('requested_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_adjustments_contract_id'), 'contract_adjustments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_adjustments_id'), 'contract_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_contract_adjustments_reference_year'), 'contract_adjustments', ['reference_year'], unique=False)
    op.create_index(op.f('ix_contract_adjustments_status'), 'contract_adjustments', ['status'], unique=False)
    op.create_table('materials_medicines_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=80), nullable=False),
    sa.Column('billing_reference', sa.String(length=80), nullable=False),
    sa.Column('addition_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('reduction_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_medicines_rules_billing_reference'), 'materials_medicines_rules', ['billing_reference'], unique=False)
    op.create_index(op.f('ix_materials_medicines_rules_contract_id'), 'materials_medicines_rules', ['contract_id'], unique=False)
    op.create_index(op.f('ix_materials_medicines_rules_id'), 'materials_medicines_rules', ['id'], unique=False)
    op.create_index(op.f('ix_materials_medicines_rules_item_type'), 'materials_medicines_rules', ['item_type'], unique=False)
    op.create_table('remuneration_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('table_type', sa.String(length=50), nullable=False),
    sa.Column('reference_source', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remuneration_tables_contract_id'), 'remuneration_tables', ['contract_id'], unique=False)
    op.create_index(op.f('ix_remuneration_tables_id'), 'remuneration_tables', ['id'], unique=False)
    op.create_index(op.f('ix_remuneration_tables_name'), 'remuneration_tables', ['name'], unique=False)
    op.create_index(op.f('ix_remuneration_tables_table_type'), 'remuneration_tables', ['table_type'], unique=False)
    op.create_table('remuneration_table_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remuneration_table_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('proposed_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('adjustment_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('billing_rule', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['remuneration_table_id'], ['remuneration_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remuneration_table_items_code'), 'remuneration_table_items', ['code'], unique=False)
    op.create_index(op.f('ix_remuneration_table_items_id'), 'remuneration_table_items', ['id'], unique=False)
    op.create_index(op.f('ix_remuneration_table_items_remuneration_table_id'), 'remuneration_table_items', ['remuneration_table_id'], unique=False)
    op.create_table('negotiation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negotiation_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('contract_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_file_id'], ['contract_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['negotiation_opportunity_id'], ['negotiation_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_messages_channel'), 'negotiation_messages', ['channel'], unique=False)
    op.create_index(op.f('ix_negotiation_messages_contract_file_id'), 'negotiation_messages', ['contract_file_id'], unique=False)
    op.create_index(op.f('ix_negotiation_messages_id'), 'negotiation_messages', ['id'], unique=False)
    op.create_index(op.f('ix_negotiation_messages_message_date'), 'negotiation_messages', ['message_date'], unique=False)
    op.create_index(op.f('ix_negotiation_messages_negotiation_opportunity_id'), 'negotiation_messages', ['negotiation_opportunity_id'], unique=False)
    op.create_index(op.f('ix_negotiation_messages_user_id'), 'negotiation_messages', ['user_id'], unique=False)
    op.add_column('users', sa.Column('access_profile_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_access_profile_id'), 'users', ['access_profile_id'], unique=False)
    op.create_foreign_key('fk_users_access_profile_id_access_profiles', 'users', 'access_profiles', ['access_profile_id'], ['id'], ondelete='SET NULL')
    op.execute("DELETE FROM contracts WHERE contract_number = 'TEST-PG-LOCAL-001'")
    op.execute(
        """
        DELETE FROM operators
        WHERE name = 'Operadora Teste PostgreSQL'
          AND NOT EXISTS (
              SELECT 1 FROM contracts WHERE contracts.operator_id = operators.id
          )
        """
    )
    op.execute("DROP TABLE IF EXISTS db_health_check")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_access_profile_id_access_profiles', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_access_profile_id'), table_name='users')
    op.drop_column('users', 'access_profile_id')
    op.drop_index(op.f('ix_negotiation_messages_user_id'), table_name='negotiation_messages')
    op.drop_index(op.f('ix_negotiation_messages_negotiation_opportunity_id'), table_name='negotiation_messages')
    op.drop_index(op.f('ix_negotiation_messages_message_date'), table_name='negotiation_messages')
    op.drop_index(op.f('ix_negotiation_messages_id'), table_name='negotiation_messages')
    op.drop_index(op.f('ix_negotiation_messages_contract_file_id'), table_name='negotiation_messages')
    op.drop_index(op.f('ix_negotiation_messages_channel'), table_name='negotiation_messages')
    op.drop_table('negotiation_messages')
    op.drop_index(op.f('ix_remuneration_table_items_remuneration_table_id'), table_name='remuneration_table_items')
    op.drop_index(op.f('ix_remuneration_table_items_id'), table_name='remuneration_table_items')
    op.drop_index(op.f('ix_remuneration_table_items_code'), table_name='remuneration_table_items')
    op.drop_table('remuneration_table_items')
    op.drop_index(op.f('ix_remuneration_tables_table_type'), table_name='remuneration_tables')
    op.drop_index(op.f('ix_remuneration_tables_name'), table_name='remuneration_tables')
    op.drop_index(op.f('ix_remuneration_tables_id'), table_name='remuneration_tables')
    op.drop_index(op.f('ix_remuneration_tables_contract_id'), table_name='remuneration_tables')
    op.drop_table('remuneration_tables')
    op.drop_index(op.f('ix_materials_medicines_rules_item_type'), table_name='materials_medicines_rules')
    op.drop_index(op.f('ix_materials_medicines_rules_id'), table_name='materials_medicines_rules')
    op.drop_index(op.f('ix_materials_medicines_rules_contract_id'), table_name='materials_medicines_rules')
    op.drop_index(op.f('ix_materials_medicines_rules_billing_reference'), table_name='materials_medicines_rules')
    op.drop_table('materials_medicines_rules')
    op.drop_index(op.f('ix_contract_adjustments_status'), table_name='contract_adjustments')
    op.drop_index(op.f('ix_contract_adjustments_reference_year'), table_name='contract_adjustments')
    op.drop_index(op.f('ix_contract_adjustments_id'), table_name='contract_adjustments')
    op.drop_index(op.f('ix_contract_adjustments_contract_id'), table_name='contract_adjustments')
    op.drop_table('contract_adjustments')
    op.drop_index(op.f('ix_access_profiles_name'), table_name='access_profiles')
    op.drop_index(op.f('ix_access_profiles_id'), table_name='access_profiles')
    op.drop_table('access_profiles')
    # ### end Alembic commands ###
